### ISSUE TITLE
Likelihood

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/ctdist#8]
Likelihood is currently incorrect additively on the log scale. Issue is in the denominator.

Code as implemented in Hay et al. approach is here and may shed some light t as the equations in the SI (linked below) don't really match :

https://github.com/jameshay218/virosolver/blob/32eb908818a1ae12cafd97a143c160f222ec22fb/src/likelihoods_cpp.cpp#L234

[media-1.pdf](https://github.com/epiforecasts/ctdist/files/6078509/media-1.pdf)

**Comment by seabbs** [comment]
![Screenshot 2021-03-03 at 20 56 33](https://user-images.githubusercontent.com/20317649/109871263-f0970380-7c62-11eb-9122-3d02e96031a1.png)

**Comment by seabbs** [comment]
Varying the ct by days since infection vector so that CTs are either very high or very low early on has a big impact on the apparent bias. Choosing higher CT values early leads to an increase in infection probability whilst using very low CT values leads to a decreasing probability of infection.

**Comment by seabbs** [comment]
<img width="589" alt="Screenshot 2021-03-03 at 23 15 50" src="https://user-images.githubusercontent.com/20317649/109885439-66f13100-7c76-11eb-8149-d1504c383148.png">

Essentially we don't have the left hand side of this curve in our data but the model does not know this and so bias is introduced.

**Comment by seabbs** [comment]
Looks resolved in both #11 and #12  (though a vector needs reversing). Merge either of these and close this issue.

**Comment by jhellewell14** [comment]
I think we should merge #11 after moving some of the comments across to help code clarity. I have closed the other PR.

**Comment by seabbs** [comment]
Merged and opened #17 for adding comments.
